os: osx
language: objective-c
osx_image: xcode8.3
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - FRAMEWORK_NAME="MATRIX Streaming SDK"
before_install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - gem install xcpretty -N
script:
  - xcodebuild -version
  - xcodebuild -project "MATRIX Streaming SDK.xcodeproj" -scheme "MATRIX Streaming SDK iOS" -destination "generic/platform=iOS" -configuration "release" ONLY_ACTIVE_ARCH=NO build | xcpretty
  - pod lib lint --quick 